SELECT [SID]
      ,[TESTNUMBER]
      ,[COMPONENTID]
      ,[Date]
      ,[CHNumber]
      ,[CH_Pass_Fail]
      ,[FailureCodeID]
      ,[Case_Temp]
      ,[DDMI_Temp]
      ,[RXP1]
      ,[DDMI_RXP1]
      ,[BER1]
      ,[RXP2]
      ,[DDMI_RXP2]
      ,[BER2]
      ,[RXP3]
      ,[DDMI_RXP3]
      ,[BER3]
      ,[RXP4]
      ,[DDMI_RXP4]
      ,[BER4]
      ,[RXP5]
      ,[DDMI_RXP5]
      ,[BER5]
      ,[Symbol_Err_4.5_Media]
      ,[Symbol_Err_4.5_Host]
      ,[Symbol_Err_0_Media]
      ,[Symbol_Err_0_Host]
      ,[Delta_Media]
      ,[Delta_Host]
      ,[Location]
      ,[Port_SN]
      ,[AOIBert_SN]
  FROM [工八_PEREADONLY].[LK2MES-DB-REAL].[dbo].[V_PE_PRD_TestResult_800G_Fixed_BER_Test]
GO

