SELECT [SID]
      ,[TestNumber]
      ,[COMPONENTID]
      ,[CHNumber]
      ,[Order]
      ,[VCC]
      ,[Case_Temp]
      ,[DDMI_Temp]
      ,[DDMI_Bias]
      ,[BER]
      ,[CH_Pass_Fail]
      ,[FailureCodeID]
      ,[DDMI_TXP]
      ,[DDMI_RXP]
      ,[HP_CP(W)]
      ,[Location]
      ,[Port_SN]
      ,[AOIBert_SN]
  FROM [工八_PEREADONLY].[LK2MES-DB-REAL].[dbo].[V_PE_PRD_TestResult_800G_BER_Symbol_Error_Test]
GO

