SELECT [LIV_MASTER_SID]
      ,[TESTNUMBER]
      ,[WO]
      ,[LOT]
      ,[LOTTYPE]
      ,[COMPONENTID]
      ,[OPERATION]
      ,[TESTTYPEID]
      ,[DEVICE]
      ,[DEVICETYPE]
      ,[EQUPMENT]
      ,[TOOLNAME]
      ,[COMMENT]
      ,[TABLENAME]
      ,[TESTSTATUS]
      ,[TESTRESULT]
      ,[TESTREASON]
      ,[FIXTUREID]
      ,[CREATEUSERID]
      ,[CREATETIME]
      ,[USERID]
      ,[UPDATETIME]
      ,[CURRENTOPERATION]
  FROM [工八_PEREADONLY].[LK2MES-DB-REAL].[dbo].[V_PE_PRD_TESTRESULT_LIV_LE_MASTER]
GO

